### PR TITLE
try to read report file name from env

### PR DESCRIPTION
**Pull request by john-hu**
@michaelleeallen 

This pull request adds the code to use env.TEST_REPORT_FILENAME as the file name, if it is found.

### CODE REVIEW

**Comment by michaelleeallen** [comment]
@john-hu Thanks for the PR! Can you add a quick unit test to verify this, please?

**Comment by michaelleeallen** [comment]
@john-hu There needs to be a corresponding update to the README file explaining the new environment variable "TEST_REPORT_FILENAME".

**Comment by john-hu** [comment]
@michaelleeallen I had add a unit test for this case.

We have to move the const into the reporter function because the `process.env` is used at the first `require` statement. After that, I cannot change any constants. So, I had moved the those two lines to reporter function..

**Comment by john-hu** [comment]
BTW, why travis cannot install npm libraries?? I didn't touch anything at package.json....

**Comment by john-hu** [comment]
`libxmljs-mt` is installed failed.

**Comment by john-hu** [comment]
According to [master branch report](https://travis-ci.org/michaelleeallen/jest-junit-reporter/builds/203547333), it was red at 8 hours ago...... :'(

**Comment by michaelleeallen** [comment]
It looks like travis is trying to download v0.16.1 of libxmljs-mt instead of 0.18x. Not sure why, but will investigate further.

**Comment by michaelleeallen** [comment]
So, travis-ci does not include an updated g++ compiler- which has to be present for libxmljs-mt to install. @john-hu Please pull in the latest changes from master into this PR. Thanks.

**Comment by john-hu** [comment]
@michaelleeallen  Sorry for late reply.... I got  really busy few weeks ago... Please review this patch and give me some suggestions.....

BTW, it would be nice to have two commits in review procedure. But to squash two commits into one is better for code releasing. Please tell me which one you prefer..... Thanks...

**Comment by michaelleeallen** [comment]
@john-hu the two commits here are fine, so no need to squash.

**Pull request merged**
